Models/Payments.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace IHLA_Template.Models
{
	public class Payments
	{
		public long PaymentID = 0;
		public long ParentID = 0;
		public decimal Credit = 0.00m;
		public decimal Charge = 0.00m;
		public decimal Total = 0.00m;
		public DateTime Date;


		public List<Payments> GetAllPaymentsForParent(long ParentID)
		{
			try {

				Database db = new Database();

				SqlConnection cn = new SqlConnection();
				if (!db.GetDBConnection(ref cn)) throw new Exception("Database did not connect");
				SqlDataAdapter da = new SqlDataAdapter("vParentsBilling", cn);
				List<Payments> paymentList = new List<Payments>();

				da.SelectCommand.CommandType = CommandType.StoredProcedure;

				db.SetParameter(ref da, "@intParentID", ParentID, SqlDbType.NVarChar);

				try {
					DataSet ds = new DataSet();
					da.Fill(ds);

					int rowCount = ds.Tables[0].Rows.Count;

					if (rowCount > 0) {

						for (int i = 0; i < rowCount; i++) {
							Payments newPayment = new Payments();
							DataRow dr = ds.Tables[0].Rows[i];
							newPayment.ParentID = ParentID;
							newPayment.Credit = (decimal)dr["decCredit"];
							newPayment.Charge = (decimal)dr["decCharge"];
							newPayment.Total = (decimal)dr["decTotal"];
							newPayment.Date = (DateTime)dr["dtmDate"];

							paymentList.Add(newPayment);
						}
					}
				}
				catch (Exception ex) { throw new Exception(ex.Message); }
				finally {
					db.CloseDBConnection(ref cn);
				}
				return paymentList;
			}
			catch (Exception ex) {
				throw new Exception(ex.Message);
			}
		}

		public long InsertPayment(Payments p)
		{
			try {
				Database db = new Database();
				SqlConnection cn = null;
				if (!db.GetDBConnection(ref cn)) throw new Exception("Database did not connect");
				SqlCommand cm = new SqlCommand("INSERT_Billing", cn);
				long intUID = -1;

				db.SetParameter(ref cm, "@uid", p.PaymentID, SqlDbType.BigInt, Direction: ParameterDirection.Output);
				db.SetParameter(ref cm, "@intParentID", p.ParentID, SqlDbType.NVarChar);
				db.SetParameter(ref cm, "@decCharge", p.Charge, SqlDbType.Decimal);
				db.SetParameter(ref cm, "@decCredit", p.Credit, SqlDbType.Decimal);
				db.SetParameter(ref cm, "@dtmDate", DateTime.Now, SqlDbType.DateTime);

				//db.SetParameter(ref cm, "ReturnValue", 0, SqlDbType.TinyInt, Direction: ParameterDirection.ReturnValue);

				cm.ExecuteReader();

				intUID = (long)cm.Parameters["@uid"].Value;
				db.CloseDBConnection(ref cn);

				if (intUID == -1) throw new Exception("Payment ID not created");

				return intUID;
			}
			catch (Exception ex) { throw new Exception(ex.Message); }
		}
	}
	 
}

Controllers/AdminController.cs
using IHLA_Template.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IHLA_Template.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {

			AdminModel am = new AdminModel();
			am.AdminUser = am.AdminUser.GetUserSession();

			DateTime dtmToday = DateTime.Now;
			string strToday = dtmToday.ToString("yyyy") + "-" + dtmToday.ToString("MM") + "-" + dtmToday.ToString("dd");

			am.UpcomingTours = am.GetUpcomingTours(strToday);

			am.PendingStudentList = am.GetPendingStudentList();
			am.PendingEmployeeList = am.GetPendingEmployeeList();

			if (am.AdminUser.UID > 0) {
				return View(am);
			}
			else {
				return RedirectToAction("Login", "Profile");
			}
        }

		public ActionResult Payments()
		{
			Parent p = new Parent();
			var parents = p.GetAllParentsItemList();
			ViewData["Parents"] = parents;

			return View();
		}

		[HttpPost]
		public ActionResult Payments(FormCollection col)
		{
			try {
				Payments p = new Payments();

				p.ParentID = Int32.Parse(col["ParentID"]);
				p.Date = DateTime.Now;
				if (col["Charge"] != "") {
					p.Charge = Convert.ToDecimal(col["Charge"]);
				}
				if (col["Credit"] != "") {
					p.Credit = Convert.ToDecimal(col["Credit"]);
				}

				p.PaymentID = p.InsertPayment(p);
				if (p.PaymentID > 0) {
					ViewBag.Message = "Record Added: #" + p.PaymentID;
				}

				Parent par = new Parent();
				var parents = par.GetAllParentsItemList();
				ViewData["Parents"] = parents;

				return View();
			}
			catch(Exception ex) {
				ViewBag.Message = "Failed to add record: " + ex.Message;

				Parent par = new Parent();
				var parents = par.GetAllParentsItemList();
				ViewData["Parents"] = parents;

				return View();
			}
		}

		public ActionResult PendingStudents()
		{

			AdminModel am = new AdminModel();
			am.AdminUser = am.AdminUser.GetUserSession();

			am.PendingStudentList = am.GetPendingStudentList();

			if (am.AdminUser.UID > 0) {
				return View(am);
			}
			else {
				return RedirectToAction("Login", "Profile");
			}
		}


		public ActionResult StudentApplication(FormCollection col)
		{
			var states = States.GetStatesList();
			ViewData["States"] = states;

			var	studentID = col["btnSubmit"];
			


			AdminModel am = new AdminModel();
			am.AdminUser = am.AdminUser.GetUserSession();

			//Get Student by Student ID
			am.StudentApplicant = am.GetStudentByStudentID(studentID);
			var statename = states.First(c => c.Value == am.StudentApplicant.State.ToString());
			ViewData["StudentState"] = statename.Text;
			//Get ParentID by StudentID
			//Get Parent by ParentID
			am.ParentApplicant = am.GetParentByStudentID(studentID);
			statename = states.First(c => c.Value == am.ParentApplicant.State.ToString());
			ViewData["ParentState"] = statename.Text;

			if (am.AdminUser.UID > 0) {
				return View(am);
			}
			else {
				return RedirectToAction("Login", "Profile");
			}
		}

		public ActionResult EmployeeApplication(FormCollection col)
		{
			var states = States.GetStatesList();
			ViewData["States"] = states;

			var EmployeeID = col["btnSubmit"];

			AdminModel am = new AdminModel();
			am.AdminUser = am.AdminUser.GetUserSession();

			//Get Student by Employee ID
			am.EmployeeApplicant = am.GetEmployeeByEmployeeID(EmployeeID);
			var statename = states.First(c => c.Value == am.EmployeeApplicant.State.ToString());
			ViewBag.state = statename.Text;

			if (am.AdminUser.UID > 0)
			{
				ViewBag.ID = EmployeeID;
				return View(am.EmployeeApplicant);
			}
			else
			{
				return RedirectToAction("Login", "Profile");
			}
		}

		public ActionResult PendingEmployee()
		{

			AdminModel am = new AdminModel();
			am.AdminUser = am.AdminUser.GetUserSession();

			am.PendingEmployeeList = am.GetPendingEmployeeList();

			if (am.AdminUser.UID > 0)
			{
				return View(am);
			}
			else
			{
				return RedirectToAction("Login", "Profile");
			}
		}


		public ActionResult AdminEmployeeApproval(FormCollection col)
		{
			int UID = Int32.Parse(col["ID"]);
			int approval = Int32.Parse(col["Approval"]);
			int Flag = 0;

			AdminEmployeeApproval AEA = new AdminEmployeeApproval();

			Flag = AEA.AdminEmployeeApprove(UID, approval);

			switch (Flag)
            {
				case 1:
					ViewBag.CompletionFlag = "Employee has been approved!";
					break;
				case 2:
					ViewBag.CompletionFlag = "Employee has been denied!";
					break;
				default:
					ViewBag.CompletionFlag = "Error. Please contact the System admin.";
					break;
			}

			return View();
		}


		public ActionResult AdminFamilyPage(int UID)
		{
			AdminFamilyPage AFP = new AdminFamilyPage();

			List<AdminFamilyPageParentInfo> P = new List<AdminFamilyPageParentInfo>();

			P = AFP.GetParentByStudentUserID(UID);

			ViewBag.ChildFirstName = AFP.StudentsFirstName;
			ViewBag.ChildLastName = AFP.StudentsLastName;
			ViewBag.ChildDOB = AFP.Age;

			return View(P);
		}

		public ActionResult AdminFamilyDeletion(int UID)
		{
			AdminFamilyDelete AFD = new AdminFamilyDelete();

			ViewBag.CompletionFlag = AFD.AdminFamilyDeletion(UID);

			return View();
		}

		public ActionResult AddEvent()
		{
			return View();
		}

		[HttpPost]
		public ActionResult AddEvent(FormCollection col)
		{
			try {
				AdminModel am = new AdminModel();

				am.NewEvent.Event = col["NewEvent.Event"];
				am.NewEvent.EventDate = Convert.ToDateTime(col["NewEvent.EventDate"]);
				am.NewEvent.Time = col["Time"];
				am.NewEvent.Description = col["NewEvent.Description"];

				var successFlag = am.InsertNewEvent(am.NewEvent);

				if (successFlag > 0) {
					ViewBag.Message = "Event successfully added";
				}
				else {
					ViewBag.Message = "Error adding event";
				}
			}
			catch(Exception ex) {
				ViewBag.Message = "Event successfully added";
			}

			return View();
		}

		[HttpPost]
		public ActionResult ApproveStudent(FormCollection col)
		{
			try {
				AdminModel am = new AdminModel();

				var studentID = col["btnSubmit"];

				var intStudentID = Convert.ToInt32(studentID);

				am.EnrollStudent(intStudentID);


				return View();
			}
			catch {
				return RedirectToAction("Error", "Shared");
			}
		}
	}
}

Controllers/StudentApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHLA_Template.Models;

namespace IHLA_Template.Controllers
{
    public class StudentApplicationController : Controller
    {
		public ActionResult Index()
		{
			return View();
		}

        // GET: StudentApplication
        public ActionResult Application()
        {
			var states = States.GetStatesList();
			ViewData["States"] = states;
			ViewBag.Title = "Application";
			ViewBag.Message = "Application for employment:";

			return View();
		}

		[HttpPost]
		public ActionResult Application(FormCollection col)
		{
			try {
				int successFlag = -1;
				User u = new User();
				StudentApplication su = new StudentApplication();

				u = u.GetUserSession();

				// Get student info from form to model
				su.student.FirstName = col["student.FirstName"];
				su.student.LastName = col["student.LastName"];
				su.student.DateOfBirth = col["student.DateOfBirth"];
				su.student.ExpectedStartDate = col["student.ExpectedStartDate"].ToString();
				su.student.Address = col["student.Address"];
				su.student.City = col["student.City"];
				su.student.State = Int32.Parse(col["student.State"]); // col["StudentState"];
				su.student.ZipCode = col["student.ZipCode"];
				su.student.HomePhoneNumber = col["student.HomePhoneNumber"];

				su.student.HasAllergy = col["Allergy"];
				su.student.AllergyInterventionRequired = col["AllergyIntervention"];
				su.student.HasSpecialHealthCondition = col["HealthCondition"];
				su.student.HealthcareInterventionRequired = col["HealthConditionIntervention"];
				su.student.HasMedication = col["Medication"];
				su.student.MedicationInterventionRequired = col["MedicationIntervention"];
				su.student.HasDietaryRestriction = col["DietaryRestrictions"];
				su.student.DietaryInterventionRequired = col["DietaryRestrictionsIntervention"];
				if (col["student.AdditionalInformation"] != "") {
					su.student.AdditionalInformation = col["student.AdditionalInformation"] + "; ";
				}

				if (su.student.HasAllergy == "1") {
					su.student.AdditionalInformation += "ALLERGY: " + col["AllergyDescription"] + "; ";
				}
				if (su.student.HasSpecialHealthCondition == "1") {
					su.student.AdditionalInformation += "HEALTH CONDITION: " + col["HealthConditionDescription"] + "; ";
				}
				if (su.student.HasMedication == "1") {
					su.student.AdditionalInformation += "MEDICATION: " + col["MedicationDescription"] + "; ";
				}
				if (su.student.HasDietaryRestriction == "1") {
					su.student.AdditionalInformation += "DIETARY RESTRICTION: " + col["DietaryRestrictionsDescription"] + "; ";
				}

				if (su.student.AdditionalInformation == "") {
					su.student.AdditionalInformation = "none";
				}
				// Insert Student
				su.student.StudentID = su.InsertStudent(su);

				// Special Information

				if (su.student.HasAllergy == "1") {
					su.InsertChildAllergyJoin(1, su.student);
				}
				if (su.student.AllergyInterventionRequired == "1") {
					su.InsertChildAllergyJoin(2, su.student);
				}
				
				if (su.student.HasSpecialHealthCondition == "1") {
					su.InsertChildAllergyJoin(3, su.student);
				}
				if(su.student.HealthcareInterventionRequired == "1") {
					su.InsertChildAllergyJoin(4, su.student);
				}
				
				if (su.student.HasMedication == "1") {
					su.InsertChildAllergyJoin(5, su.student);
				}
				if (su.student.MedicationInterventionRequired == "1") {
					su.InsertChildAllergyJoin(6, su.student);
				}
				
				if (su.student.HasDietaryRestriction == "1") {
					su.InsertChildAllergyJoin(7, su.student);
				}
				if (su.student.DietaryInterventionRequired == "1") {
					su.InsertChildAllergyJoin(8, su.student);
				}


				// Get primary parent info 
				su.parent1.FirstName = col["parent1.FirstName"];
				su.parent1.LastName = col["parent1.LastName"];
				su.parent1.RelationshipToChild = col["parent1.RelationshipToChild"];
				su.parent1.Address = col["parent1.Address"];
				su.parent1.City = col["parent1.City"];
				su.parent1.State = Int32.Parse(col["parent1.State"]);
				su.parent1.ZipCode = col["parent1.ZipCode"];
				su.parent1.HomePhoneNumber = col["parent1.HomePhoneNumber"];
				su.parent1.MobilePhoneNumber = col["parent1.MobilePhoneNumber"];
				su.parent1.WorkPhoneNumber = col["parent1.WorkPhoneNumber"];
				su.parent1.WorkName = col["parent1.WorkName"];
				su.parent1.WorkAddress = col["parent1.WorkAddress"];
				su.parent1.WorkCity = col["parent1.WorkCity"];
				su.parent1.LoginInID = u.UID.ToString();
				su.parent1.Email = u.Email;
				// Insert Parent
				su.parent1.UID = su.InsertParent(su.parent1);
				//Update User ID parent flag
				u.IsParent = "Y";
				var at = u.Save();
				if (at != Models.User.ActionTypes.UpdateSuccessful) 
					{
						throw new Exception("Parent Flag not Updated");
					}

				// Insert StudentParent Record
				successFlag = su.InsertParentChildJoin(su.parent1, su.student);

				// Get Emergency contact info
				su.emergencyContact.FirstName = col["emergencyContact.FirstName"];
				su.emergencyContact.LastName = col["emergencyContact.LastName"];
				su.emergencyContact.RelationshipToChild = col[".emergencyContact.RelationshipToChild"];
				su.emergencyContact.City = col["emergencyContact.City"];
				su.emergencyContact.State = Int32.Parse(col["emergencyContact.State"]);
				su.emergencyContact.PhoneNumber = col["emergencyContact.PhoneNumber"];
				su.emergencyContact.OtherPhoneNumber = col["emergencyContact.OtherPhoneNumber"];
				// Insert Emergency Contact
				su.emergencyContact.UID = su.InsertEmergencyContact(su.emergencyContact);
				// Insert Student-Emergency Contact Join
				successFlag = su.InsertChildEmergencyContactJoin(su.emergencyContact, su.student);

				// Get physician info
				su.physician.PhysicianName = col["physician.PhysicianName"];
				su.physician.PhysicianStreetAddress = col["physician.PhysicianStreetAddress"];
				su.physician.PhysicianCity = col["physician.PhysicianCity"];
				su.physician.PhysicianState = Int32.Parse(col["physician.PhysicianState"]);
				su.physician.PhysicianPhoneNumber = col["physician.PhysicianPhoneNumber"];
				//Insert Physician
				su.physician.UID = su.InsertPhysician(su.physician);
				//Insert Student-Physician Join
				successFlag = su.InsertChildPhysicianJoin(su.physician, su.student);
				

				return RedirectToAction("Success");
			}
			catch (Exception ex) {
				return RedirectToAction("Error", "Home");
			}
		}

		public ActionResult Success()
		{
			return View();
		}

		public ActionResult SignUp()
		{
			Models.User u = new Models.User();
			return View(u);
		}

		[HttpPost]
		public ActionResult SignUp(FormCollection col)
		{
			try {
				Models.User u = new Models.User();

				u.FirstName = col["FirstName"];
				u.LastName = col["LastName"];
				u.Email = col["Email"];
				u.UserID = col["UserID"];
				u.Password = col["Password"];

				if (u.FirstName.Length == 0 || u.LastName.Length == 0 || u.Email.Length == 0 || u.UserID.Length == 0 || u.Password.Length == 0) {
					u.ActionType = Models.User.ActionTypes.RequiredFieldsMissing;
					ViewBag.Message = "Required fields missing. Please try again";
					return View(u);
				}
				else {
					if (col["btnSubmit"] == "signup") { //sign up button pressed
						Models.User.ActionTypes at = Models.User.ActionTypes.NoType;
						at = u.Save();
						switch (at) {
							case Models.User.ActionTypes.InsertSuccessful:
								u.SaveUserSession();
								return RedirectToAction("Application");
							case Models.User.ActionTypes.DuplicateEmail:
								ViewBag.Message = "Email already used. Please try again";
								return View();
							case Models.User.ActionTypes.DuplicateUserID:
								ViewBag.Message = "User ID already used. Please try again";
								return View();
							//break;
							default:
								return View(u);
								//break;
						}
					}
					else {
						return View(u);
					}
				}
			}
			catch (Exception) {
				Models.User u = new Models.User();
				return View(u);
			}
		}

		public ActionResult LogIn()
		{
			Models.User u = new Models.User();

			return View();
		}

		[HttpPost]
		public ActionResult LogIn(FormCollection col)
		{
			try {
				Models.User u = new Models.User();

				if (col["btnSubmit"] == "signin") {
					u.UserID = col["UserID"];
					u.Password = col["Password"];

					u = u.Login();
					if (u != null && u.UID > 0) {
						
							u.SaveUserSession();
							return RedirectToAction("Application");
						
					}
					else {
						u = new Models.User();
						u.UserID = col["UserID"];
						u.ActionType = Models.User.ActionTypes.LoginFailed;
						ViewBag.Message = "Invalid Username or Password. Please try again";
					}
				}

				return View(u);
			}
			catch (Exception) {
				Models.User u = new Models.User();
				return View(u);
			}
		}
	}
}

Views/Admin/AdminFamilyPage.cshtml
@model IEnumerable<IHLA_Template.Models.AdminFamilyPageParentInfo>
@{
    ViewBag.Title = "AdminFamilyPage";
}

<h2 class="jumbotron text-center">Admin Family Manager</h2>

<div>

    @foreach (var item in Model)
    {
        <div class="s-member-div">
            <ul>
                <li>@item.LastName , @item.FirstName</li>
                <li>@item.PhoneNumber</li>
            </ul>
        </div>
        <div align="right">
            <button class="btn btn-danger" onclick="location.href='@Url.Action("AdminFamilyDelete", "Admin",new { UID = item.ParentUID})'">Remove</button>
        </div>
    }
  
    <div class="s-member-div">
        <ul>
            <li>@ViewBag.ChildFirstName @ViewBag.ChildLastName</li>
            <li>@ViewBag.ChildDOB</li>
        </ul>
    </div>
    <br />
    <div class="form-inline">
        <button class="btn btn-success">Add Parent</button>
    </div>
</div>

Views/Admin/EmployeeApplication.cshtml
@model IHLA_Template.Models.EmployeeApplications
@{
    /**/

    /**/

    /**/

    ViewBag.Title = "Application";
}

<h2 class="jumbotron">Employee Application</h2>

@{ IHLA_Template.Models.User u = new IHLA_Template.Models.User();
    u = u.GetUserSession();
    if (u.IsAdmin == "Y")
    {

        <div class="section">
            <h4> Employee Information</h4>
            <div class="item">
                <div>@Html.LabelFor(model => model.FirstName, "First Name")</div>
                <div>@Html.DisplayFor(model => model.FirstName)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.LastName, "Last Name")</div>
                <div>@Html.DisplayFor(model => model.LastName)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.Address)</div>
                <div>@Html.DisplayFor(model => model.Address)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.City)</div>
                <div>@Html.DisplayFor(model => model.City)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.State)</div>
                <div>@ViewBag.state</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.Zip)</div>
                <div>@Html.DisplayFor(model => model.Zip)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.PhoneNumber, "Phone Number")</div>
                <div>@Html.DisplayFor(model => model.PhoneNumber)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.Email)</div>
                <div>@Html.DisplayFor(model => model.Email)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.EmergencyContact, "Emergency Contact")</div>
                <div>@Html.DisplayFor(model => model.EmergencyContact)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.EmergecyNumber, "Emergecy Number")</div>
                <div>@Html.DisplayFor(model => model.EmergecyNumber)</div>
            </div>
        </div>
        <div class="section">
            <h4>Eligiblies</h4>
            <div class="item">
                <div>@Html.LabelFor(model => model.UsaEligible, "Can work in Usa?")</div>
                <div>@Html.DisplayFor(model => model.UsaEligible)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.Misdemeanor)</div>
                <div>@Html.DisplayFor(model => model.Misdemeanor)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.Felony)</div>
                <div>@Html.DisplayFor(model => model.Felony)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.CovictionExplained, "Conviction explation")</div>
                <div>@Html.DisplayFor(model => model.CovictionExplained)</div>
            </div>
        </div>
        <div class="section">
            <h4>Eligiblies</h4>
            <div class="item">
                <div>@Html.LabelFor(model => model.FirstName, "Full Time")</div>
                <div>@Html.DisplayFor(model => model.FirstName)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.PartTime, "Part Time")</div>
                <div>@Html.DisplayFor(model => model.PartTime)</div>
            </div>
        </div>
        <div class="section">
            <h4>Skills and certs</h4>
            <div class="item">
                <div>@Html.LabelFor(model => model.Skills, "Skills")</div>
                <div>@Html.DisplayFor(model => model.Skills)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.Certs, "Certification")</div>
                <div>@Html.DisplayFor(model => model.Certs)</div>
            </div>
        </div>
        <div class="section">
            <h4>Questionare</h4>
            <div class="item">
                <div>@Html.LabelFor(model => model.CareerGoals, "Career Goals")</div>
                <div>@Html.DisplayFor(model => model.CareerGoals)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.HireYou, "Why should we hire you?")</div>
                <div>@Html.DisplayFor(model => model.HireYou)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.ProConduct, "Professional Conduct")</div>
                <div>@Html.DisplayFor(model => model.Misdemeanor)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.CustService, "Customer Service")</div>
                <div>@Html.DisplayFor(model => model.CustService)</div>
            </div>
            <div class="item">
                <div>@Html.LabelFor(model => model.ToyFight, "Toy Fight problem")</div>
                <div>@Html.DisplayFor(model => model.ToyFight)</div>
            </div>
        </div>

       
            using (Html.BeginForm("AdminEmployeeApproval", "Admin", FormMethod.Post))
            {
                <input type="hidden" name="ID" value="@ViewBag.ID" />
                <input type="hidden" name="Approval" value="1" />
                <button id="btnSubmit" name="btnSubmit" class="btn btn-success"> Approve</button>
            }

            <br/>    

            using (Html.BeginForm("AdminEmployeeApproval", "Admin", FormMethod.Post))
            {
                <input type="hidden" name="ID" value="@ViewBag.ID" />
                <input type="hidden" name="Approval" value="2" />
                <button id="btnSubmit" name="btnSubmit" class="btn btn-success"> Deny</button>
            }

            <br/>

        <a class="btn btn-success" href=" ~/Admin/PendingEmployee">Back</a>

    }

    else
    {
        <h4>Please Log-in or Sign-up before starting an application</h4>
        <br />
        <h5>@Html.ActionLink("Log-In", "Login", "StudentApplication")</h5>
        <h5>@Html.ActionLink("SignUp", "SignUp", "StudentApplication")</h5>
    }
}

Views/Admin/Index.cshtml
@model IHLA_Template.Models.AdminModel


@{
	if (Model.AdminUser.IsAdmin == "Y") {
		<h3 style="font-size:36px; color:purple; font-family:'Comic Sans MS'; padding-bottom:1em;">Welcome Back, @Model.AdminUser.FirstName </h3>

		<div class="s-member-div" style="background-color:forestgreen; color:white; border-radius:15px;">
			<h3 align="center"><u>Upcoming Tours</u></h3>
			@foreach (var item in Model.UpcomingTours)
			{
				<table class="table" style="font-size:18px" >
					<tr>
						<th>Name</th>
						<th>Date</th>
						<th>Time</th>
					</tr>
					<tr>
						<td>@(item.FirstName + " " + item.LastName)</td>
						<td>@item.Date</td>
						<td>@item.Time</td>
					</tr>
				</table>
			}
		</div>
        <div class="button-holder">
			<div>
				<a class="button-large" href=" ~/Admin/PendingStudents" style="margin-right:4.5em;">Pending Student Applications: @Model.PendingStudentList.Count()</a>
				<a class="button-large" href=" ~/Admin/PendingEmployee">Pending Employee Applications: @Model.PendingEmployeeList.Count()</a>
			</div>
			
			<a class="button-superxl" href=" ~/Home/AdminManageClasses">Manage Classes</a>
            @Html.ActionLink("Manage Payments", "Payments", "Admin", new { @class = "button-superxl" })
            @Html.ActionLink("Add Event", "AddEvent", "Admin", new { @class = "button-superxl" })
        </div>

	}
	else {
		<h4>Sorry, Admin Access only</h4>

	}
}